# version: '3.8'

services:

  api:
    build: ./car_testing_api
    container_name: car-classification-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://car_user:car_password@postgres:5432/car_classification
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - adv-net
  
  web:
    build: ./hosting
    container_name: car-classification-web
    ports:
      - "8080:8080"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - adv-net

  postgres:
    image: postgres:16
    container_name: car-classification-db
    environment:
      - POSTGRES_USER=car_user
      - POSTGRES_PASSWORD=car_password
      - POSTGRES_DB=car_classification

    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - adv-net
  
  nginx:
    image: nginx:latest
    container_name: car-classification-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - web
    restart: unless-stopped
    networks:
      - adv-net
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ""
    networks:
      - adv-net

networks:
  adv-net:
    driver: bridge
